# version here is only relevant for the AppVeyor CI, no need to adjust
version: '{build}'

environment:
  global:
    PYTHON_LOC: "C:\\Miniconda36-x64"

install:
  - call %PYTHON_LOC%\Scripts\activate.bat
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

build_script:
  - echo   - vs2015_runtime ==14.0.25420 >> environment.yml
  - conda env create --file environment.yml
  - call %PYTHON_LOC%\Scripts\activate.bat cate-env
  - python setup.py install
  - conda list
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  - set NUMBA_DISABLE_JIT=1
  # Uncomment following line if web testing on travis breaks our build
  - set CATE_DISABLE_WEB_TESTS=1
  # geopandas in tests break the build on appveyor (maybe the problem of gdal?)
  - set CATE_DISABLE_GEOPANDAS_TESTS=1
  - set CATE_DISABLE_PLOT_TESTS=1
  - set CATE_DISABLE_CLI_UPDATE_TESTS=1
  - py.test -v --cov=cate test
