# version here is only relevant for the AppVeyor CI, no need to adjust
version: '{build}'

image:
  - macOS
  - Ubuntu2004

platform:
  - x64

environment:
  # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
  NUMBA_DISABLE_JIT: 1
  # Uncomment following line if web testing breaks our build
  CATE_DISABLE_WEB_TESTS: 1
  # geopandas in tests break the build on appveyor (maybe the problem of gdal?)
  CATE_DISABLE_GEOPANDAS_TESTS: 1
  CATE_DISABLE_PLOT_TESTS: 1
  CATE_DISABLE_CLI_UPDATE_TESTS: 1

for:
-
  matrix:
    only:
      - image: macOS
  install:
    - curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
-
  matrix:
    only:
      - image: Ubuntu2004
  install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda

build_script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --set channel_priority strict
  - conda update -q conda
  - conda info -a
  - conda init bash
  - export CONDA_BASE=$(conda info --base)
  - source $CONDA_BASE/etc/profile.d/conda.sh
  - conda install -c conda-forge -n base mamba pip

  - git clone https://github.com/dcs4cop/xcube.git
  - git clone https://github.com/dcs4cop/xcube-cci.git
  # Install xcube env and xcube
  - cd xcube
  - mamba env create
  - conda activate xcube
  - pip install -e .
  # Install xcube-cci
  - cd ..
  - cd xcube-cci
  - mamba install -c conda-forge lxml pydap aiohttp nest-asyncio
  - pip install -e .
  # Install cate-specific packages
  - cd ..
  - mamba install -c conda-forge cartopy
  - pip install -e .
  - conda list
  - pytest -v --cov=cate tests
