@startuml

interface Dataset {
    {abstract} schema(): Schema
    {abstract} gap_fill(): Dataset
    {abstract} time_series(): Dataset
    {abstract} subset(): Dataset
    {abstract} resample(): Dataset
    {abstract} close()
}

abstract Schema {
}

abstract DatasetAdapter implements Dataset {
    {abstract} wrapped_dataset(): object
}

class DatasetCollection implements Dataset {
}

class cdm_xarray.XarrayDatasetAdapter extends DatasetAdapter {
    wrapped_dataset(): xarray.Dataset
}

class cdm_shapefile.ShapefileDatasetAdapter extends DatasetAdapter {
    wrapped_dataset(): shapefile.Dataset
}

DatasetCollection o--> "0..N" Dataset
Dataset --> "1" Schema

note right of DatasetCollection
Collection pattern
end note

@enduml