@startuml

interface Dataset {
    {abstract} schema(): Schema
    {abstract} gapfill(): Dataset
    {abstract} timeseries(): Dataset
    {abstract} subset(): Dataset
    {abstract} resample(): Dataset
    {abstract} close()
}

abstract Schema {
}

abstract DatasetAdapter implements Dataset {
    {abstract} wrapped_dataset(): object
}

class DatasetCollection implements Dataset {
}

class cdm.xarray.XarrayDatasetAdapter extends DatasetAdapter {
    wrapped_dataset(): xarray.Dataset
}

class cdm.shapefile.ShapefileDatasetAdapter extends DatasetAdapter {
    wrapped_dataset(): shapefile.Dataset
}

DatasetCollection o--> "0..N" Dataset
Dataset --> "1" Schema

note right of DatasetCollection
Collection pattern
end note

@enduml