@startuml
participant User

User -> DatasetCollection: timeseries()
activate DatasetCollection #FFBBBB

DatasetCollection -> DatasetCollection: for dataset #1
activate DatasetCollection #DarkSalmon

DatasetCollection -> XarrayDatasetAdapter: timeseries()
activate XarrayDatasetAdapter

XarrayDatasetAdapter --> DatasetCollection
deactivate XarrayDatasetAdapter

deactivate DatasetCollection

DatasetCollection -> DatasetCollection: for dataset #2
activate DatasetCollection #DarkSalmon

DatasetCollection -> ShapefileDatasetAdapter: timeseries()
activate ShapefileDatasetAdapter

ShapefileDatasetAdapter --> DatasetCollection
deactivate ShapefileDatasetAdapter

deactivate DatasetCollection
DatasetCollection --> User
deactivate DatasetCollection

@enduml