@startuml

object globals {
    DATA_STORE_REGISTRY: DataStoreRegistry
    query_data_sources(data_stores, constraints)
    open_dataset(data_source, name, time_range)
}

note bottom of globals
Plugins can extend
DATA_STORE_REGISTRY
by adding new data stores
end note

class DataStoreRegistry {
    get_data_stores(): List[DataStore]
    get_data_store(name): DataStore
    add_data_store(DataStore): void
    remove_data_store(DataStore): void
}

interface DataStore {
    name: str
    {abstract} query(query_expr): DataSource
}

interface DataSource {
    name: str
    {abstract} get_dataset_schema(): cdm.Schema
    {abstract} open_dataset(name, time_range): xarray.Dataset
    {abstract} sync(time_range)
}

DataStoreRegistry o--> "N" DataStore
DataStore  ..>  DataSource: <provide>


@enduml