@startuml

object globals {
    DATA_STORE_REGISTRY: DataStoreRegistry
    query_data_sources(data_stores, constraints)
    open_dataset(data_stores, name)
}

note bottom of globals
Plugins can extend
DATA_STORE_REGISTRY
by adding new data stores
end note

class DataStoreRegistry {
    get_data_stores(): List[DataStore]
    get_data_store(name): DataStore
    add_data_store(DataStore): void
    remove_data_store(DataStore): void
}

interface DataStore {
    {abstract} query(constraints): DataSource
}

interface DataSource {
    {abstract} get_dataset_schema()
    {abstract} open_dataset(constraints): cdm.Dataset
    {abstract} sync(time_range)
}

DataStoreRegistry o--> "N" DataStore
DataStore  ..>  DataSource: <provide>

DataSource ..>  interface cdm.Dataset: <open>
DataSource ..>  interface cdm.Schema: <provide>



@enduml