@startuml

class CatalogRegistry {
    get_catalogs(name): Catalog
    add_catalog(Catalog): void
    remove_catalog(Catalog): void
}

interface Catalog {
    {abstract} query(filter): DataSource
}

interface DataSource {
    {abstract} open_dataset(constraints): cdm.Dataset
}

class FileSetCatalog implements Catalog {
    root_dir
    query(filter): DataSource
}

class FileSetDataSource implements DataSource {
    name
    base_dir
    file_pattern
    open_dataset(constraints): cdm.Dataset
}

class FileSetInfo  {
    info_update_time
    start_time
    end_time
    num_files
    size_in_mb
}

CatalogRegistry o--> "N" Catalog
Catalog  ..>  DataSource: <provide>

DataSource ..>  interface cdm.Dataset: <open>


FileSetCatalog "1" o-- "N" FileSetDataSource
FileSetDataSource -- "0..1" FileSetInfo

note left of FileSetCatalog
Users may create their own.
The default instance mirrors
the CCI Portal's FTP tree.
end note

note left of FileSetDataSource
open_dataset() will look for
actual file types and return
either an xarray or shapefile
Dataset instance.
end note

@enduml