@startuml


node "CCI_Toolbox_Core" {
    package "ect.ds" {
        DS - [esa_cci_ftp]
        [more data stores...] #white
    }

    package ect.ops {
        OP-[timeseries]
        [gapfill]
        [resample]
        [filter]
        [plot]
        [more operations...] #white
    }

    package "ect.core" {
        [cdm]
        [io]

        [op]
        [workflow]
    }

    package "ect.ui" {
        CLI - [cli]
        WebAPI - [ws]
    }
}

node "CCI_Toolbox_GUI" {
    package "ect.gui" {
        [web_app]
    }
}

cloud {
node "CCI_Data_Access_Portal" #eeeeee {
    FTP - [ftp_service]
    [more services...] #white
}
}


[io] ..> [cdm]
[workflow] ..> [op]
[esa_cci_ftp] ..> FTP
[esa_cci_ftp] ..> io

ect.ops .r.> [cdm]

[web_app] --> WebAPI

@enduml