@startuml


node "CCI_Toolbox_Core" {
    package "cate.ds" {
        [esa_cci_odp]
        [esa_cci_ftp]
        [more data store modules...] #white
    }

    package cate.ops {
        [coregistration]
        [correlation]
        [harmonize]
        [io]
        [plot]
        [resampling]
        [select]
        [subset]
        [timeseries]
        [more operation modules...] #white
    }

    package "cate.core" {
        [ds]
        [monitor]
        [objectio]
        [op]
        [plugin]
        [util]
        [workflow]
    }

    package "cate.ui" {
        [cli]
        [webapi]
    }
}

node "CCI_Toolbox_GUI" {
    package "cate.gui" {
        [webapp]
    }
}

cloud {
node "CCI_Open_Data_Portal" #eeeeee {
    [FTP]
    [HTTP]
    [OPeNDAP]
    [more services...] #white
}
}

[cli] ..> [webapi]
[webapp] ..> [webapi]

[workflow] ..> [op]

cate.ui .r.> cate.ops
cate.ui .r.> cate.ds
cate.ds .r.> CCI_Open_Data_Portal


@enduml