@startuml


node "CCI_Toolbox_Core" {
    package "ect.ds" {
        [esa_cci_odp]
        [esa_cci_ftp]
        [more data store modules...] #white
    }

    package ect.ops {
        [coregistration]
        [correlation]
        [harmonize]
        [io]
        [plot]
        [resampling]
        [select]
        [subset]
        [timeseries]
        [more operation modules...] #white
    }

    package "ect.core" {
        [ds]
        [monitor]
        [objectio]
        [op]
        [plugin]
        [util]
        [workflow]
    }

    package "ect.ui" {
        [cli]
        [webapi]
    }
}

node "CCI_Toolbox_GUI" {
    package "ect.gui" {
        [webapp]
    }
}

cloud {
node "CCI_Open_Data_Portal" #eeeeee {
    [FTP]
    [HTTP]
    [OPeNDAP]
    [more services...] #white
}
}

[cli] ..> [webapi]
[webapp] ..> [webapi]

[workflow] ..> [op]

ect.ui .r.> ect.ops
ect.ui .r.> ect.ds
ect.ds .r.> CCI_Open_Data_Portal


@enduml