@startuml

interface ValueSource {
    {abstract} get_value()
}

class ConstantValueSource implements ValueSource {
    constant
    get_value()
}

class ParameterValueSource implements ValueSource {
    value
    get_value()
    set_value(value)
}

class NodeInput {
    name: str
}

class NodeOutput implements ValueSource {
    name: str
    value: object
    targets: List[NodeInput]
    get_value()
    set_value(value)
}


abstract class Node {
}

Node "1" o-- "0..N" NodeInput
Node "1" o-- "0..N" NodeOutput

NodeInput --> "0..1" ValueSource : source

@enduml