@startuml

Node : id: str
Node --> OpMetaInfo: op_meta_info
Node : input_connectors: List[InputConnectors]
Node : output_connectors: List[OutputConnectors]

OpNode --|> Node
OpNode : op: OpRegistration

Graph --|> Node
Graph : nodes: List[Node]
'Graph --> "0..N" Node: nodes

OpMetaInfo : qualfied_name : str
OpMetaInfo : header : OrderedDict
OpMetaInfo : input : OrderedDict
OpMetaInfo : output : OrderedDict

note as N1
Collection pattern
end note

@enduml