@startuml


abstract class Node {
    id : str
}

class NodeConnector {
    node: Node
    name: str
    source: NodeConnector
    value: object
}

Node o--> "0..N" NodeConnector : input
Node o--> "0..N" NodeConnector : output

NodeConnector --> NodeConnector
NodeConnector --> Node

@enduml
