@startuml

interface cate.ui.workspace.WorkspaceManager {
    init_workspace()
    set_workspace_resource()
    write_workspace_resource()
}

class cate.ui.workspace.FSWorkspaceManager implements cate.ui.workspace.WorkspaceManager {
}

class cate.ui.workspace.WebAPIWorkspaceManager implements cate.ui.workspace.WorkspaceManager {
}

interface cate.ui.webapi.WebService {
}

class cate.ui.workspace.Workspace {
}



cate.ui.workspace.WebAPIWorkspaceManager ..> cate.ui.webapi.WebService: <communicate>
cate.ui.workspace.FSWorkspaceManager ..--> cate.ui.workspace.Workspace: <uses>
cate.ui.workspace.FSWorkspaceManager o--> "0..N" cate.ui.workspace.Workspace: workspace_cache
cate.ui.webapi.WebService o--> "1" cate.ui.workspace.FSWorkspaceManager
cate.ui.workspace.Workspace --> "1" cate.core.workflow.Workflow

cate.core.workflow.Workflow o--> "0..N" cate.core.workflow.OpStep

@enduml