@startuml

abstract Node {
    id : str
    inputs : Dict[str, NodePort]
    outputs : Dict[str, NodePort]
    {abstract} from_json(json_dict)
    {abstract} to_json_dict() : dict
    {abstract} invoke(monitor, **args)
}

class Workflow extends Node {
    from_json(json_dict)
    to_json_dict() : dict
    invoke(monitor, **args)
}

abstract class Step extends Node {
}

class WorkflowStep extends Step {
    resource : str
}

class OpStep extends Step {
    op_registration : Operation
}

class ExprStep extends Step {
    expression : str
}

class SubProcessStep extends Step {
    arguments : List[str]
}

class NoOpStep extends Step {
}

class cate.core.op.OpMetaInfo {
    qualified_name : str
    header : dict
    inputs : dict
    outputs : dict
}

WorkflowStep --> Workflow: workflow
OpStep o--> cate.core.op.Operation
Node o--> cate.core.op.OpMetaInfo: op_meta_info
Workflow o--> "0..N" Step: steps
Step --> Node : parent


note left of Workflow
Collection pattern:
a Workflow is a Node,
and aggregates Steps,
which are Nodes as well.
end note

@enduml