@startuml

abstract Node {
    id: str
    input: NodeInputNamespace
    output: NodeOutputNamespace
    invoke()
}

class OpNode implements Node {
    invoke()
}

class Graph implements Node {
    invoke()
}


class op.OpMetaInfo {
    qualified_name : str
    header : OrderedDict
    input : OrderedDict
    output : OrderedDict
}


OpNode --> op.OpRegistration : op_registration
Node --> op.OpMetaInfo: op_meta_info
Graph o--> "0..N" Node: nodes


note left of Graph
Collection pattern
end note

@enduml