@startuml


abstract class Node {
    id : str
}

class NodePort {
    node: Node
    name: str
    source: NodePort
    value: object
}

Node o--> "0..N" NodePort : inputs
Node o--> "0..N" NodePort : outputs

NodePort --> NodePort
NodePort --> Node

@enduml
