@startuml

abstract class Writer {
    description: str
    format_name: str
    filename_ext: str
    write(obj, file_path, **args)
    can_write(obj, **args): bool
}

class TextWriter extends Writer {
}

class JsonWriter extends Writer {
}

class Netcdf4Writer extends Writer {
}

class Netcdf3Writer extends Writer {
}

class WriterRegistry {
    writers: List
    find_writer(obj, format, ext): Writer
}

WriterRegistry o--> "N" Writer

object globals {
    find_writer(obj, file_path, format_name)
    writer_obj(obj, file_path, format_name)
    WRITER_REGISTRY: WriterRegistry
}

note left of globals
WRITER_REGISTRY contains all known
writer instances.
end note

@enduml