@startuml

abstract class Monitor {
    {static} NULL: Monitor
    {abstract} start(self, label: str, total_work: float)
    {abstract} progress(self, work: float = None, msg: str)
    {abstract} done(self)
    child(self, work: float): Monitor
    cancel()
    is_cancelled(): bool
}

class ConsoleMonitor implements Monitor {
}

class ChildMonitor implements Monitor {
}


ChildMonitor o--> "1" Monitor : parent_monitor


@enduml