@startuml
participant User

User -> Workflow: invoke()
activate Workflow #FFBBBB

Workflow -> Workflow: for all steps
activate Workflow #DarkSalmon

Workflow -> OpStep: invoke()
activate OpStep

OpStep -> operation: _call_()
activate OpStep

operation --> OpStep
deactivate OpStep
OpStep --> Workflow
deactivate OpStep
deactivate Workflow
Workflow --> User
deactivate Workflow

@enduml