name: Deploy on Release

on: workflow_dispatch

jobs:
#  build-docker:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set Release Name
#        id: releasename
#        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          registry: quay.io
#          username: ${{ secrets.QUAY_DOCKER_REPO_USERNAME }}
#          password: ${{ secrets.QUAY_DOCKER_REPO_PASSWORD }}
#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: docker/Dockerfile
#          push: true
#          tags: quay.io/ccitools/cate:${{ steps.releasename.outputs.VERSION }}
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Name
        id: releasename
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
        with:
          repository: bcdev/k8s-configs
          token: ${{ secrets.CATE_GITHUB_K8S_CONFIGS_PAT }}

      - name: clone k8s-config
        run: |
          cd k8s-configs/ke/helm/xcube-hub
          sed -i -e 's/cate-version [a-z0-9\.]*$/cate-version ${{ steps.releasename.outputs.VERSION }}/g' values-dev.yaml
          git commit -a -m "Updated cate version to ${{ steps.releasename.outputs.VERSION }}"
          git push origin main
