name: Unittest Cate

on: push

jobs:
  unittest:
    env:
      XCUBE_VERSION: 0.8.2.dev0
      XCUBE_CCI_VERSION: 0.8.1.dev6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get-xcube
        shell: bash
        run: |
          wget https://github.com/dcs4cop/xcube/archive/v"${XCUBE_VERSION}".tar.gz
          tar xvzf v"${XCUBE_VERSION}".tar.gz
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube
          environment-file: cd xcube-"${XCUBE_VERSION}"/environment.yml
      - name: setup-xcube
        shell: bash -l {0}
        run: |
          cd xcube-"${XCUBE_VERSION}"

          python setup.py install
          cd ..
      - name: setup-xcube-cci
        shell: bash -l {0}
        run: |
          wget https://github.com/dcs4cop/xcube-cci/archive/v"${XCUBE_CCI_VERSION}".tar.gz
          tar xvzf v"${XCUBE_CCI_VERSION}".tar.gz
          cd xcube-cci-"${XCUBE_CCI_VERSION}"
          python setup.py install
          mamba install -y -c conda-forge aiohttp nest-asyncio lxml pydap cartopy
      - name: setup-cate
        shell: bash -l {0}
        run: |
          conda info
          conda list
          source activate xcube & python setup.py develop
      - name: unittest-cate
        shell: bash -l {0}
        run: |
          # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
          export NUMBA_DISABLE_JIT=1
          # Uncomment following line if web testing on travis breaks our build
          export CATE_DISABLE_WEB_TESTS=1
          # geopandas in tests break the build on appveyor (maybe the problem of gdal?)
          export CATE_DISABLE_GEOPANDAS_TESTS=1
          export CATE_DISABLE_PLOT_TESTS=1
          export CATE_DISABLE_CLI_UPDATE_TESTS=1
          py.test -v --cov=cate tests
