name: Unittest Cate

on: push

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: cate-env
          environment-file: environment.yml
      - name: setup-cate
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python setup.py develop
      - name: unittest-cate
        shell: bash -l {0}
        run: |
          # For the unit-tests, disable Numba JIT, otherwise Coverage wont reach the actual Python code
          export NUMBA_DISABLE_JIT=1
          # Uncomment following line if web testing on travis breaks our build
          export CATE_DISABLE_WEB_TESTS=1
          # geopandas in tests break the build on appveyor (maybe the problem of gdal?)
          export CATE_DISABLE_GEOPANDAS_TESTS=1
          export CATE_DISABLE_PLOT_TESTS=1
          py.test -v --cov=cate tests
